//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ookii.Dialogs.WinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ookii.Dialogs.WinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to load the progress dialog animation: {0}.
        /// </summary>
        internal static string AnimationLoadErrorFormat {
            get {
                return ResourceManager.GetString("AnimationLoadErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The credential target may not be an empty string..
        /// </summary>
        internal static string CredentialEmptyTargetError {
            get {
                return ResourceManager.GetString("CredentialEmptyTargetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred acquiring credentials..
        /// </summary>
        internal static string CredentialError {
            get {
                return ResourceManager.GetString("CredentialError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PromptForCredentialsWithSave has not been called or the credentials were modified after the call..
        /// </summary>
        internal static string CredentialPromptNotCalled {
            get {
                return ResourceManager.GetString("CredentialPromptNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The task dialog already has a non-custom button with the same type..
        /// </summary>
        internal static string DuplicateButtonTypeError {
            get {
                return ResourceManager.GetString("DuplicateButtonTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The task dialog already has an item with the same id..
        /// </summary>
        internal static string DuplicateItemIdError {
            get {
                return ResourceManager.GetString("DuplicateItemIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file &quot;{0}&quot; could not be found..
        /// </summary>
        internal static string FileNotFoundFormat {
            get {
                return ResourceManager.GetString("FileNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The current operating system does not support glass, or the Desktop Window Manager is not enabled..
        /// </summary>
        internal static string GlassNotSupportedError {
            get {
                return ResourceManager.GetString("GlassNotSupportedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid filter string,.
        /// </summary>
        internal static string InvalidFilterString {
            get {
                return ResourceManager.GetString("InvalidFilterString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The id of a task dialog item must be higher than 0..
        /// </summary>
        internal static string InvalidTaskDialogItemIdError {
            get {
                return ResourceManager.GetString("InvalidTaskDialogItemIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The item is not associated with a task dialog..
        /// </summary>
        internal static string NoAssociatedTaskDialogError {
            get {
                return ResourceManager.GetString("NoAssociatedTaskDialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot change the id for a standard button..
        /// </summary>
        internal static string NonCustomTaskDialogButtonIdError {
            get {
                return ResourceManager.GetString("NonCustomTaskDialogButtonIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preview.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The progress dialog is not shown..
        /// </summary>
        internal static string ProgressDialogNotRunningError {
            get {
                return ResourceManager.GetString("ProgressDialogNotRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The progress dialog is already running..
        /// </summary>
        internal static string ProgressDialogRunning {
            get {
                return ResourceManager.GetString("ProgressDialogRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A custom button or radio button cannot have an empty label..
        /// </summary>
        internal static string TaskDialogEmptyButtonLabelError {
            get {
                return ResourceManager.GetString("TaskDialogEmptyButtonLabelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cross-thread operation not valid: Task dialog accessed from a thread other than the thread it was created on while it is visible..
        /// </summary>
        internal static string TaskDialogIllegalCrossThreadCallError {
            get {
                return ResourceManager.GetString("TaskDialogIllegalCrossThreadCallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The task dialog item already belongs to another task dialog..
        /// </summary>
        internal static string TaskDialogItemHasOwnerError {
            get {
                return ResourceManager.GetString("TaskDialogItemHasOwnerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The task dialog must have buttons..
        /// </summary>
        internal static string TaskDialogNoButtonsError {
            get {
                return ResourceManager.GetString("TaskDialogNoButtonsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The task dialog is not current displayed..
        /// </summary>
        internal static string TaskDialogNotRunningError {
            get {
                return ResourceManager.GetString("TaskDialogNotRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The task dialog is already being displayed..
        /// </summary>
        internal static string TaskDialogRunningError {
            get {
                return ResourceManager.GetString("TaskDialogRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The operating system does not support task dialogs..
        /// </summary>
        internal static string TaskDialogsNotSupportedError {
            get {
                return ResourceManager.GetString("TaskDialogsNotSupportedError", resourceCulture);
            }
        }
    }
}
